import { useState, useEffect } from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'
import { Map } from '@/components'
// import Datamap from 'datamaps'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [map, setMap] = useState(null);
  const [counter, setCounter] = useState(0);
  useEffect(() => {

    // if (counter > 5) {
    //   // const map_obj = new Datamap({
    //   //   element: document.getElementById('container'),
    //   //   geographyConfig: {
    //   //     highlightOnHover: false,
    //   //     popupOnHover: false
    //   //   }
    //   // });
    //   // setMap(map_obj);
    // }
    // else {
    //   // await a second
    //   setTimeout(() => {
    //     setCounter(counter + 1);
    //   }, 1000);
    // }
  }, [counter]);
  return (
    <>
      <Head>
        <title>Mapa de probabilidad de brotes EFE y Dengue</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={ `${styles.main} ${inter.className}` }>
        <div id="container" className={ `${styles.mapContainer}` } >
          <Map />
        </div>
      </main>
    </>
  )
}
